##############
# Adyen Test #
##############


library(DescTools)
library(ggplot2)
library(maps)

# Increase limit for max.print, 800k+ rows were omitted
?options
options(max.print=999999)

# Read CSV "loan.csv" file #
Original_Loan_File <- read.csv("C://Users//Brandon Wong//Documents//Adyen_Test//wetransfer-937f2c//data-analysis-test//loan.csv", header = TRUE, sep = ",")

dim(Original_Loan_File)
View(head(Original_Loan_File))
str(Original_Loan_File)
names(Original_Loan_File)

###################################################
### Question 1: Provide a distribution of loans ###
###################################################


mean(Original_Loan_File$loan_amnt, na.rm = TRUE) # mean = 14766.26
sd(Original_Loan_File$loan_amnt) # standard deviation = 8435.456
quantile(Original_Loan_File$loan_amnt, c(.25, .5, .75)) # 25th percentile = 8000. 50th = 13000, 75th = 20000
# http://stackoverflow.com/questions/22256881/proportional-bar-plot-with-ggplot2 #
# http://www.stat.umn.edu/geyer/old/5101/rlook.html #

## http://www.statmethods.net/advgraphs/probability.html ->
# Applied loans are normally distributed with a mean of 14766.26 and a standard deviation of 8435.456,
# what proportion of applied loans are expected to have a value between 10k and 20k?

mean=14766.26; sd=8435.456
lb=10000; ub=20000

x <- seq(-4,4,length=100)*sd + mean
hx <- dnorm(x,mean,sd)

plot(x, hx, type="n", xlab="Applied Loan Amount ($)", ylab="Density",
     main="Normal Distribution of Applied Loans", axes=FALSE)

i <- x >= lb & x <= ub
lines(x, hx)
polygon(c(lb,x[i],ub), c(0,hx[i],0), col="red") 

area <- pnorm(ub, mean, sd) - pnorm(lb, mean, sd)
result <- paste("P(",lb,"< Applied Loan <",ub,") =",
                signif(area, digits=3))
mtext(result,3)
axis(1, at=seq(-10000, 40000, 10000), pos=0)

### Using DescTools package, one can view the 1. Density graph, 2. Box and Whisker plot, 3. Empirical CDF plot
Desc(Original_Loan_File$loan_amnt, plotit = TRUE, main = "Applied Loan Amount")

Original_Loan_File$issue_d <- as.Date(gsub("^", "01-", Original_Loan_File$issue_d), format="%d-%b-%Y")

amnt_df <- Original_Loan_File %>% 
  select(issue_d, loan_amnt) %>% 
  group_by(issue_d) %>% 
  summarise(Amount = sum(loan_amnt))

ts_amnt <- ggplot(amnt_df, 
                  aes(x = issue_d, y = Amount))
ts_amnt + geom_line() + xlab("Date issued")

###################################################
### Question 2: What is the lowest loan amount? ### QUESTION: loans applied or loans given?
###################################################

min(Original_Loan_File$loan_amnt, na.rm = TRUE)

####################################################
### Question 3: What is the highest loan amount? ###
####################################################

max(Original_Loan_File$loan_amnt, na.rm = TRUE)


##############################################################################
### Question 4: Provide a graph that visualizes the issued loans over time ###
##############################################################################

amnt_df_grade <- Original_Loan_File %>% 
  select(issue_d, loan_amnt, grade) %>% 
  group_by(issue_d, grade) %>% 
  summarise(Amount = sum(loan_amnt))

ts_amnt_grade <- ggplot(amnt_df_grade, 
                        aes(x = issue_d, y = Amount))
ts_amnt_grade + geom_area(aes(fill=grade)) + xlab("Date issued")

###################################################################
### Question 5: Provide a graph that visualizes the loan status ###
###################################################################

Desc(Original_Loan_File$loan_status, plotit = T)


# This graph shows the distribution of loan amounts by status
box_status <- ggplot(Original_Loan_File, aes(loan_status, loan_amnt))
box_status + geom_boxplot(aes(fill = loan_status)) +
  theme(axis.text.x = element_blank()) +
  labs(list(
    title = "Loan Amount By Status",
    x = "Status",
    y = "Amount"))  


####################################################################################################
### Question 6: Provide a graph that visualizes the REASON people took out a loan in percentages ###
####################################################################################################

Desc(loanbook$purpose, main = "Loan purposes", plotit = TRUE)
Desc(loanbook$title, main = "Loan titles", plotit = TRUE)
